import type { WorkspaceFile } from './types';

export interface ProductRequirements {
  intent:string;
  needsBackend:boolean;
  needsValidation:boolean;
  needsAuth:boolean;
  needsDatabase:boolean;
  integrations:string[];
  entities:string[];
}

function has(text:string,re:RegExp){return re.test(text)}

export function inferProductRequirements(prompt:string,intent:string):ProductRequirements{
  const p=String(prompt||'').toLowerCase();
  const business=['crm','store','dashboard'].includes(intent);
  const integrations:string[]=[];
  const known:[string,RegExp][]=[
    ['supabase',/supabase/],
    ['firebase',/firebase/],
    ['datajud',/datajud/],
    ['djen',/djen|di[aá]rio de justi[cç]a/],
    ['github',/github/],
    ['vercel',/vercel/],
    ['stripe',/stripe|pagamento|checkout/],
    ['rest-api',/\bapi\b|endpoint|webhook|integra[cç][aã]o|integration/]
  ];
  for(const [name,re] of known)if(re.test(p))integrations.push(name);

  const needsAuth=has(p,/login|auth|usu[aá]rio|perfil|permiss[aã]o|rbac|multi.?user|equipe/)||business;
  const needsDatabase=has(p,/banco|database|postgres|supabase|firebase|persist|salvar|dados|registros/)||business;
  const needsValidation=has(p,/valid|formul[aá]rio|cadastro|cpf|cnpj|email|telefone|valor|finance|cliente/)||business;
  const needsBackend=needsDatabase||needsAuth||integrations.length>0||has(p,/backend|server|segredo|secret|cron|job|fila/);

  const entities=intent==='crm'
    ? ['Lead','Customer','Opportunity','Invoice','Activity','Integration']
    : intent==='store'
      ? ['Product','Cart','Order','Customer','Payment']
      : intent==='dashboard'
        ? ['Metric','Event','Report','Filter']
        : ['Record'];

  return {intent,needsBackend,needsValidation,needsAuth,needsDatabase,integrations:Array.from(new Set(integrations)),entities};
}

function envExample(req:ProductRequirements){
  const lines=[
    '# Generated by PredictLM — keep secrets server-side',
    'VITE_API_URL=http://localhost:8787'
  ];
  if(req.integrations.includes('supabase'))lines.push('SUPABASE_URL=','SUPABASE_ANON_KEY=','SUPABASE_SERVICE_ROLE_KEY=');
  if(req.integrations.includes('firebase'))lines.push('FIREBASE_PROJECT_ID=','FIREBASE_CLIENT_EMAIL=','FIREBASE_PRIVATE_KEY=');
  if(req.integrations.includes('datajud'))lines.push('DATAJUD_API_KEY=');
  if(req.integrations.includes('github'))lines.push('GITHUB_TOKEN=');
  if(req.integrations.includes('vercel'))lines.push('VERCEL_TOKEN=');
  if(req.integrations.includes('stripe'))lines.push('STRIPE_SECRET_KEY=','VITE_STRIPE_PUBLISHABLE_KEY=');
  if(req.integrations.includes('rest-api'))lines.push('EXTERNAL_API_BASE_URL=','EXTERNAL_API_KEY=');
  return lines.join('\n')+'\n';
}

function validationModule(intent:string){
  const crm=intent==='crm';
  return `export type ValidationErrors=Record<string,string>;

export function required(value:unknown,label='Campo'){
  return String(value??'').trim()?null:label+' é obrigatório.';
}
export function validEmail(value:unknown){
  const v=String(value??'').trim();
  if(!v)return null;
  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(v)?null:'Email inválido.';
}
export function validPhone(value:unknown){
  const v=String(value??'').replace(/\\D/g,'');
  if(!v)return null;
  return v.length>=10&&v.length<=13?null:'Telefone inválido.';
}
export function validMoney(value:unknown,label='Valor'){
  const n=Number(value);
  return Number.isFinite(n)&&n>=0?null:label+' deve ser um número maior ou igual a zero.';
}
export function sanitizeText(value:unknown,max=180){
  return String(value??'').replace(/[<>]/g,'').trim().slice(0,max);
}
${crm?`
export function validateLead(input:any){
  const errors:ValidationErrors={};
  const name=required(input?.name,'Nome');if(name)errors.name=name;
  const email=validEmail(input?.email);if(email)errors.email=email;
  const phone=validPhone(input?.phone);if(phone)errors.phone=phone;
  const value=validMoney(input?.value,'Valor');if(value)errors.value=value;
  const mrr=validMoney(input?.mrr,'MRR');if(mrr)errors.mrr=mrr;
  return errors;
}
`:''}
`;
}

function httpModule(){
  return `export class ApiError extends Error{
  status:number;
  payload:any;
  constructor(message:string,status=0,payload:any=null){super(message);this.status=status;this.payload=payload}
}

export async function requestJson<T>(url:string,init:RequestInit={},attempts=2):Promise<T>{
  let last:any;
  for(let attempt=0;attempt<=attempts;attempt++){
    const controller=new AbortController();
    const timer=setTimeout(()=>controller.abort(),12000);
    try{
      const response=await fetch(url,{
        ...init,
        signal:controller.signal,
        headers:{Accept:'application/json','Content-Type':'application/json',...(init.headers||{})}
      });
      const text=await response.text();
      let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}
      if(!response.ok)throw new ApiError(data?.error||data?.message||('HTTP '+response.status),response.status,data);
      return data as T;
    }catch(error){
      last=error;
      if(attempt>=attempts)throw error;
      await new Promise(r=>setTimeout(r,350*Math.pow(2,attempt)));
    }finally{clearTimeout(timer)}
  }
  throw last;
}
`;
}

function integrationModule(req:ProductRequirements){
  const rows=req.integrations.map(name=>`  {id:'${name}',enabled:true,mode:'server-proxy'}`).join(',\n');
  return `export type IntegrationStatus={id:string;enabled:boolean;mode:'server-proxy'|'browser-safe'};

export const integrationCatalog:IntegrationStatus[]=[
${rows||"  {id:'rest-api',enabled:false,mode:'server-proxy'}"}
];

export function integrationSummary(){
  return integrationCatalog.map(x=>x.id+': '+(x.enabled?'planned':'optional')).join(', ');
}
`;
}

function domainTypes(req:ProductRequirements){
  if(req.intent==='crm'){
    return `export type LeadStatus='Novo'|'Qualificado'|'Proposta'|'Fechado';
export interface Lead{
  id:number|string;
  name:string;
  company:string;
  email?:string;
  phone?:string;
  status:LeadStatus;
  value:number;
  mrr:number;
  owner:string;
  last:string;
  createdAt?:string;
  updatedAt?:string;
}
export interface Invoice{
  id:string;
  client:string;
  value:number;
  status:'Pendente'|'Pago'|'Atrasado';
  due:string;
}
`;
  }
  return req.entities.map(x=>`export interface ${x}{id:string|number;createdAt?:string;updatedAt?:string}`).join('\n');
}

function serverProxy(req:ProductRequirements){
  const allowed=req.integrations;
  return `import http from 'node:http';

const PORT=Number(process.env.PORT||8787);
const json=(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'http://localhost:5173','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'});res.end(JSON.stringify(body));};

function env(name){const value=process.env[name];if(!value)throw new Error('Missing server variable '+name);return value}

async function externalProxy(req,res){
  const url=new URL(req.url||'/', 'http://localhost');
  const integration=url.searchParams.get('integration')||'';
  const allow=${JSON.stringify(allowed)};
  if(!allow.includes(integration))return json(res,400,{error:'Integration not allowed'});

  // Provider-specific adapters belong here. Keep service-role/API secrets on server.
  return json(res,501,{error:'Configure the '+integration+' adapter before production use.'});
}

http.createServer(async(req,res)=>{
  if(req.method==='OPTIONS')return json(res,204,{});
  const url=new URL(req.url||'/', 'http://localhost');
  if(url.pathname==='/api/health')return json(res,200,{ok:true,service:'predict-app'});
  if(url.pathname==='/api/integrations')return json(res,200,{configured:${JSON.stringify(allowed)}});
  if(url.pathname==='/api/proxy')return externalProxy(req,res);
  return json(res,404,{error:'Not found'});
}).listen(PORT,()=>console.log('API http://localhost:'+PORT));
`;
}

function docs(req:ProductRequirements,prompt:string){
  return [
    '# Production Readiness',
    '',
    'Original request: '+prompt,
    '',
    '## Architecture contract',
    '- Sidebar/navigation for products with 3+ workflows.',
    '- Domain validation before mutation.',
    '- Loading, empty, success and error states.',
    '- API calls isolated from visual components.',
    '- Server-only secrets never embedded in browser code.',
    '- Persistent/shared business data requires a backend/database.',
    '- Export must contain runnable setup and environment documentation.',
    '',
    '## Detected',
    '- Backend: '+(req.needsBackend?'required':'optional'),
    '- Validation: '+(req.needsValidation?'required':'basic'),
    '- Authentication boundary: '+(req.needsAuth?'required/planned':'not requested'),
    '- Database: '+(req.needsDatabase?'required/planned':'not requested'),
    '- Integrations: '+(req.integrations.join(', ')||'none explicitly requested'),
    '- Entities: '+req.entities.join(', '),
    '',
    '## Ship gate',
    'Do not call the app complete while visible controls are inert, validation is missing, API integrations are fake, or build/tests fail.'
  ].join('\n');
}

export function buildProjectScaffold(prompt:string,intent:string):WorkspaceFile[]{
  const req=inferProductRequirements(prompt,intent);
  const files:WorkspaceFile[]=[
    {path:'src/types/domain.ts',language:'typescript',content:domainTypes(req)},
    {path:'src/domain/validation.ts',language:'typescript',content:validationModule(intent)},
    {path:'src/integrations/http.ts',language:'typescript',content:httpModule()},
    {path:'src/integrations/index.ts',language:'typescript',content:integrationModule(req)},
    {path:'PRODUCTION_READINESS.md',language:'markdown',content:docs(req,prompt)}
  ];
  if(req.needsBackend){
    files.push({path:'server/integrations.mjs',language:'javascript',content:serverProxy(req)});
    files.push({path:'.env.example',language:'text',content:envExample(req)});
  }
  return files;
}
