import type { WorkspaceFile } from './types';

export interface ProductRequirements {
  intent:string;
  needsBackend:boolean;
  needsValidation:boolean;
  needsAuth:boolean;
  needsDatabase:boolean;
  integrations:string[];
  entities:string[];
}

function has(text:string,re:RegExp){return re.test(text)}

export function inferProductRequirements(prompt:string,intent:string):ProductRequirements{
  const p=String(prompt||'').toLowerCase();
  const business=['crm','store','dashboard'].includes(intent);
  const integrations:string[]=[];
  const known:[string,RegExp][]=[
    ['supabase',/supabase/],
    ['firebase',/firebase/],
    ['datajud',/datajud/],
    ['djen',/djen|di[aá]rio de justi[cç]a/],
    ['github',/github/],
    ['vercel',/vercel/],
    ['stripe',/stripe|pagamento|checkout/],
    ['rest-api',/\bapi\b|endpoint|webhook|integra[cç][aã]o|integration/]
  ];
  for(const [name,re] of known)if(re.test(p))integrations.push(name);

  const needsAuth=has(p,/login|auth|usu[aá]rio|perfil|permiss[aã]o|rbac|multi.?user|equipe/)||business;
  const needsDatabase=has(p,/banco|database|postgres|supabase|firebase|persist|salvar|dados|registros/)||business;
  const needsValidation=has(p,/valid|formul[aá]rio|cadastro|cpf|cnpj|email|telefone|valor|finance|cliente/)||business;
  const needsBackend=needsDatabase||needsAuth||integrations.length>0||has(p,/backend|server|segredo|secret|cron|job|fila/);

  const entities=intent==='crm'
    ? ['Lead','Customer','Opportunity','Invoice','Activity','Integration']
    : intent==='store'
      ? ['Product','Cart','Order','Customer','Payment']
      : intent==='dashboard'
        ? ['Metric','Event','Report','Filter']
        : ['Record'];

  return {intent,needsBackend,needsValidation,needsAuth,needsDatabase,integrations:Array.from(new Set(integrations)),entities};
}

function envExample(req:ProductRequirements){
  const lines=[
    '# Generated by PredictLM — keep secrets server-side',
    'VITE_API_URL=http://localhost:8787'
  ];
  if(req.integrations.includes('supabase'))lines.push('SUPABASE_URL=','SUPABASE_ANON_KEY=','SUPABASE_SERVICE_ROLE_KEY=');
  if(req.integrations.includes('firebase'))lines.push('FIREBASE_PROJECT_ID=','FIREBASE_CLIENT_EMAIL=','FIREBASE_PRIVATE_KEY=');
  if(req.integrations.includes('datajud'))lines.push('DATAJUD_API_KEY=');
  if(req.integrations.includes('github'))lines.push('GITHUB_TOKEN=');
  if(req.integrations.includes('vercel'))lines.push('VERCEL_TOKEN=');
  if(req.integrations.includes('stripe'))lines.push('STRIPE_SECRET_KEY=','VITE_STRIPE_PUBLISHABLE_KEY=');
  if(req.integrations.includes('rest-api'))lines.push('EXTERNAL_API_BASE_URL=','EXTERNAL_API_KEY=');
  return lines.join('\n')+'\n';
}

function validationModule(intent:string){
  const crm=intent==='crm';
  return `export type ValidationErrors=Record<string,string>;

export function required(value:unknown,label='Campo'){
  return String(value??'').trim()?null:label+' é obrigatório.';
}
export function validEmail(value:unknown){
  const v=String(value??'').trim();
  if(!v)return null;
  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(v)?null:'Email inválido.';
}
export function validPhone(value:unknown){
  const v=String(value??'').replace(/\\D/g,'');
  if(!v)return null;
  return v.length>=10&&v.length<=13?null:'Telefone inválido.';
}
export function validMoney(value:unknown,label='Valor'){
  const n=Number(value);
  return Number.isFinite(n)&&n>=0?null:label+' deve ser um número maior ou igual a zero.';
}
export function sanitizeText(value:unknown,max=180){
  return String(value??'').replace(/[<>]/g,'').trim().slice(0,max);
}
${crm?`
export function validateLead(input:any){
  const errors:ValidationErrors={};
  const name=required(input?.name,'Nome');if(name)errors.name=name;
  const email=validEmail(input?.email);if(email)errors.email=email;
  const phone=validPhone(input?.phone);if(phone)errors.phone=phone;
  const value=validMoney(input?.value,'Valor');if(value)errors.value=value;
  const mrr=validMoney(input?.mrr,'MRR');if(mrr)errors.mrr=mrr;
  return errors;
}
`:''}
`;
}

function httpModule(){
  return `export class ApiError extends Error{
  status:number;
  payload:any;
  constructor(message:string,status=0,payload:any=null){super(message);this.status=status;this.payload=payload}
}

export async function requestJson<T>(url:string,init:RequestInit={},attempts=2):Promise<T>{
  let last:any;
  for(let attempt=0;attempt<=attempts;attempt++){
    const controller=new AbortController();
    const timer=setTimeout(()=>controller.abort(),12000);
    try{
      const response=await fetch(url,{
        ...init,
        signal:controller.signal,
        headers:{Accept:'application/json','Content-Type':'application/json',...(init.headers||{})}
      });
      const text=await response.text();
      let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}
      if(!response.ok)throw new ApiError(data?.error||data?.message||('HTTP '+response.status),response.status,data);
      return data as T;
    }catch(error){
      last=error;
      if(attempt>=attempts)throw error;
      await new Promise(r=>setTimeout(r,350*Math.pow(2,attempt)));
    }finally{clearTimeout(timer)}
  }
  throw last;
}
`;
}

function integrationModule(req:ProductRequirements){
  const rows=req.integrations.map(name=>`  {id:'${name}',required:true}`).join(',\n');
  return `export type IntegrationState='configured'|'missing'|'error'|'unknown';
export type IntegrationStatus={id:string;required:boolean;state:IntegrationState;detail?:string};

export const integrationCatalog=[
${rows||"  {id:'rest-api',required:false}"}
] as const;

export async function readIntegrationStatus(base='/api'){
  const response=await fetch(base+'/integrations',{headers:{Accept:'application/json'}});
  if(!response.ok)throw new Error('Integration status HTTP '+response.status);
  return response.json();
}

export async function testIntegration(id:string,base='/api'){
  const response=await fetch(base+'/integrations/test',{
    method:'POST',
    headers:{'Content-Type':'application/json'},
    body:JSON.stringify({integration:id})
  });
  const data=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(data?.error||('Integration test HTTP '+response.status));
  return data;
}
`;
}

function domainTypes(req:ProductRequirements){
  if(req.intent==='crm'){
    return `export type LeadStatus='Novo'|'Qualificado'|'Proposta'|'Fechado';
export interface Lead{
  id:number|string;
  name:string;
  company:string;
  email?:string;
  phone?:string;
  status:LeadStatus;
  value:number;
  mrr:number;
  owner:string;
  last:string;
  createdAt?:string;
  updatedAt?:string;
}
export interface Invoice{
  id:string;
  client:string;
  value:number;
  status:'Pendente'|'Pago'|'Atrasado';
  due:string;
}
`;
  }
  return req.entities.map(x=>`export interface ${x}{id:string|number;createdAt?:string;updatedAt?:string}`).join('\n');
}

function serverProxy(req:ProductRequirements){
  const allowed=req.integrations;
  return `const allow=${JSON.stringify(allowed)};

function env(name){return String(process.env[name]||'').trim()}
export function integrationConfigured(id){
  if(id==='rest-api')return !!env('EXTERNAL_API_BASE_URL');
  if(id==='supabase')return !!env('SUPABASE_URL')&&!!(env('SUPABASE_SERVICE_ROLE_KEY')||env('SUPABASE_ANON_KEY'));
  if(id==='firebase')return !!env('FIREBASE_REST_BASE_URL')&&!!env('FIREBASE_ACCESS_TOKEN');
  if(id==='datajud')return !!env('DATAJUD_API_KEY');
  if(id==='djen')return true;
  if(id==='github')return !!env('GITHUB_TOKEN');
  if(id==='vercel')return !!env('VERCEL_TOKEN');
  if(id==='stripe')return !!env('STRIPE_SECRET_KEY');
  return false;
}
function headersFor(id){
  if(id==='rest-api')return env('EXTERNAL_API_KEY')?{Authorization:'Bearer '+env('EXTERNAL_API_KEY')}:{};
  if(id==='supabase'){
    const key=env('SUPABASE_SERVICE_ROLE_KEY')||env('SUPABASE_ANON_KEY');
    return {apikey:key,Authorization:'Bearer '+key};
  }
  if(id==='firebase')return {Authorization:'Bearer '+env('FIREBASE_ACCESS_TOKEN')};
  if(id==='datajud')return {Authorization:'APIKey '+env('DATAJUD_API_KEY')};
  if(id==='github')return {Authorization:'Bearer '+env('GITHUB_TOKEN'),'User-Agent':'Predict-App'};
  if(id==='vercel')return {Authorization:'Bearer '+env('VERCEL_TOKEN')};
  if(id==='stripe')return {Authorization:'Bearer '+env('STRIPE_SECRET_KEY')};
  return {};
}
function baseFor(id){
  if(id==='rest-api')return env('EXTERNAL_API_BASE_URL');
  if(id==='supabase')return env('SUPABASE_URL').replace(/\\/$/,'')+'/rest/v1';
  if(id==='firebase')return env('FIREBASE_REST_BASE_URL');
  if(id==='datajud')return env('DATAJUD_BASE_URL')||'https://api-publica.datajud.cnj.jus.br';
  if(id==='djen')return 'https://comunicaapi.pje.jus.br/api/v1';
  if(id==='github')return 'https://api.github.com';
  if(id==='vercel')return 'https://api.vercel.com';
  if(id==='stripe')return 'https://api.stripe.com';
  return '';
}
function safePath(value){
  const path=String(value||'/').trim();
  if(!path.startsWith('/')||path.includes('://')||path.includes('..'))throw new Error('Invalid proxy path');
  return path;
}

export function integrationStatuses(){
  return allow.map(id=>({id,configured:integrationConfigured(id),mode:'server-proxy'}));
}

export async function proxyIntegration({id,path='/',method='GET',body=''}){
  if(!allow.includes(id))return {status:400,payload:{error:'Integration not allowed'}};
  if(!integrationConfigured(id))return {status:503,payload:{error:'Integration '+id+' is missing environment configuration'}};
  const target=baseFor(id).replace(/\\/$/,'')+safePath(path);
  const verb=String(method||'GET').toUpperCase();
  if(!['GET','POST','PATCH','PUT','DELETE'].includes(verb))return {status:405,payload:{error:'Method not allowed'}};
  const upstream=await fetch(target,{
    method:verb,
    headers:{Accept:'application/json','Content-Type':'application/json',...headersFor(id)},
    ...(['POST','PATCH','PUT'].includes(verb)&&body?{body}:{})
  });
  const text=await upstream.text();
  let payload;try{payload=text?JSON.parse(text):null}catch{payload={raw:text.slice(0,5000)}}
  return {status:upstream.status,payload};
}

export async function testIntegration(id){
  if(!allow.includes(id))return {ok:false,error:'Integration not allowed'};
  if(!integrationConfigured(id))return {ok:false,configured:false,error:'Missing environment configuration'};
  if(id==='datajud')return {ok:true,configured:true,detail:'API key present; use a tribunal-specific _search endpoint for live validation.'};
  let path='/';
  if(id==='github')path='/rate_limit';
  if(id==='stripe')path='/v1/account';
  if(id==='djen')path='/comunicacao?pagina=1&itensPorPagina=1';
  try{
    const result=await proxyIntegration({id,path,method:'GET'});
    return {ok:result.status>=200&&result.status<400,configured:true,status:result.status,detail:result.status<400?'Provider reachable':'Provider returned '+result.status};
  }catch(error){return {ok:false,configured:true,error:error?.message||String(error)}}
}
`;
}

function docs(req:ProductRequirements,prompt:string){
  return [
    '# Production Readiness',
    '',
    'Original request: '+prompt,
    '',
    '## Architecture contract',
    '- Sidebar/navigation for products with 3+ workflows.',
    '- Domain validation before mutation.',
    '- Loading, empty, success and error states.',
    '- API calls isolated from visual components.',
    '- Sidebar + subbar/navigation model separated from domain rules.',
    '- Integration screen reflects backend configuration; no fake toggle may claim a provider is connected.',
    '- Server-only secrets never embedded in browser code.',
    '- Persistent/shared business data requires a backend/database.',
    '- Export must contain runnable setup and environment documentation.',
    '',
    '## Detected',
    '- Backend: '+(req.needsBackend?'required':'optional'),
    '- Validation: '+(req.needsValidation?'required':'basic'),
    '- Authentication boundary: '+(req.needsAuth?'required/planned':'not requested'),
    '- Database: '+(req.needsDatabase?'required/planned':'not requested'),
    '- Integrations: '+(req.integrations.join(', ')||'none explicitly requested'),
    '- Entities: '+req.entities.join(', '),
    '',
    '## Ship gate',
    'Do not call the app complete while visible controls are inert, validation is missing, API integrations are fake, or build/tests fail.'
  ].join('\n');
}

function moduleSkeletons(req:ProductRequirements):WorkspaceFile[]{
  const nav=req.intent==='crm'
    ? ['Dashboard','Pipeline','Clientes','Financeiro','Integrações','Configurações']
    : req.intent==='store'
      ? ['Dashboard','Produtos','Pedidos','Clientes','Pagamentos','Configurações']
      : req.intent==='dashboard'
        ? ['Visão geral','Relatórios','Fontes','Alertas','Configurações']
        : ['Workspace','Dados','Integrações','Configurações'];

  const sidebar=`export const APP_NAV=${JSON.stringify(nav)} as const;

export function sidebarModel(active:string){
  return APP_NAV.map((label,index)=>({
    id:label.toLowerCase().normalize('NFD').replace(/\\p{M}/gu,'').replace(/[^a-z0-9]+/g,'-'),
    label,
    active:label===active,
    order:index
  }));
}
`;

  const shell=`export interface AppShellState{
  active:string;
  subbar:string[];
  loading:boolean;
  error:string|null;
}

export function createShellState(active:string,subbar:string[]=[]):AppShellState{
  return {active,subbar,loading:false,error:null};
}
`;

  const schema=`export const domainContract={
  intent:${JSON.stringify(req.intent)},
  entities:${JSON.stringify(req.entities)},
  needsAuth:${JSON.stringify(req.needsAuth)},
  needsDatabase:${JSON.stringify(req.needsDatabase)},
  needsValidation:${JSON.stringify(req.needsValidation)},
  integrations:${JSON.stringify(req.integrations)}
} as const;
`;

  const state=`export interface AsyncState<T>{data:T;loading:boolean;error:string|null;updatedAt:number|null}
export function idle<T>(data:T):AsyncState<T>{return {data,loading:false,error:null,updatedAt:null}}
export function loading<T>(state:AsyncState<T>):AsyncState<T>{return {...state,loading:true,error:null}}
export function failed<T>(state:AsyncState<T>,error:unknown):AsyncState<T>{return {...state,loading:false,error:String((error as any)?.message||error)}}
export function ready<T>(state:AsyncState<T>,data:T):AsyncState<T>{return {data,loading:false,error:null,updatedAt:Date.now()}}
`;

  const tests=`import { describe,it,expect } from 'vitest';
import { required, validEmail, validPhone, validMoney } from './validation';

describe('domain validation',()=>{
  it('rejects required empty values',()=>expect(required('','Nome')).toBeTruthy());
  it('accepts valid email',()=>expect(validEmail('user@example.com')).toBeNull());
  it('rejects short phone',()=>expect(validPhone('123')).toBeTruthy());
  it('rejects negative money',()=>expect(validMoney(-1)).toBeTruthy());
});
`;

  return [
    {path:'src/components/navigation/sidebar-model.ts',language:'typescript',content:sidebar},
    {path:'src/layout/app-shell.ts',language:'typescript',content:shell},
    {path:'src/domain/schema.ts',language:'typescript',content:schema},
    {path:'src/state/async-state.ts',language:'typescript',content:state},
    {path:'src/domain/validation.test.ts',language:'typescript',content:tests},
    {path:'src/pages/README.md',language:'markdown',content:'# Pages\n\nThe live preview is kept in App.tsx for instant sandbox execution. Production modules are split by navigation/domain responsibility for export and continued editing.\n'}
  ];
}

export function buildProjectScaffold(prompt:string,intent:string):WorkspaceFile[]{
  const req=inferProductRequirements(prompt,intent);
  const files:WorkspaceFile[]=[
    ...moduleSkeletons(req),
    {path:'src/types/domain.ts',language:'typescript',content:domainTypes(req)},
    {path:'src/domain/validation.ts',language:'typescript',content:validationModule(intent)},
    {path:'src/integrations/http.ts',language:'typescript',content:httpModule()},
    {path:'src/integrations/index.ts',language:'typescript',content:integrationModule(req)},
    {path:'PRODUCTION_READINESS.md',language:'markdown',content:docs(req,prompt)}
  ];
  if(req.needsBackend){
    files.push({path:'server/integrations.mjs',language:'javascript',content:serverProxy(req)});
    files.push({path:'.env.example',language:'text',content:envExample(req)});
  }
  return files;
}
