import type { LegalProcessBundle } from './types';

const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const date=(v?:string)=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('pt-BR')};

export function createLegalDossier(bundle:LegalProcessBundle){
  const rows=bundle.timeline.slice(0,60).map(x=>'<div class="tl"><span>'+esc(date(x.date))+'</span><div><b>'+esc(x.title)+'</b><small>'+esc(x.source)+(x.body?' · '+esc(x.body):'')+'</small></div></div>').join('');
  const lenses=bundle.lenses.map(l=>'<article class="lens '+l.level+'"><header>'+esc(l.title)+'</header><ul>'+l.findings.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul></article>').join('');
  const pubs=bundle.djen.publications.slice(0,30).map(p=>'<article class="pub"><div><b>'+esc(p.type)+'</b><span>'+esc(date(p.availableAt))+'</span></div><p>'+esc(p.text||'Sem texto normalizado')+'</p></article>').join('');

  return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dossiê '+esc(bundle.processNumber)+'</title><style>'+
  ':root{--ink:#171720;--muted:#626574;--paper:#f4f1ea;--line:#c9c5ba;--accent:#8b2942;--ok:#1f6744;--warn:#9a5b16}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Georgia,serif;line-height:1.55}.cover{background:#15151d;color:#f5f0e7;padding:55px 28px}.wrap{max-width:900px;margin:auto}.eyebrow{font:12px ui-monospace,monospace;letter-spacing:.12em;color:#c7aa70;text-transform:uppercase}.cover h1{font-size:42px;font-weight:400;letter-spacing:-.04em;margin:14px 0 8px}.cover p{color:#bdb9b2;max-width:720px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:30px;border-top:1px solid #34343d;padding-top:18px}.meta b{display:block;font:10px ui-monospace,monospace;color:#777581;text-transform:uppercase;margin-bottom:4px}.main{max-width:900px;margin:auto;padding:36px 28px 70px}.section{border-top:1px solid var(--line);padding-top:28px;margin-top:32px}.section h2{font-size:26px;font-weight:400}.summary{font-size:19px;color:#3d4050}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat{border:1px solid var(--line);padding:14px;background:#ebe7de}.stat span{display:block;font:10px ui-monospace,monospace;color:var(--muted);text-transform:uppercase}.stat b{font-size:18px}.tl{display:grid;grid-template-columns:155px 1fr;gap:18px;padding:12px 0;border-bottom:1px solid var(--line)}.tl>span{font:11px ui-monospace,monospace;color:var(--muted)}.tl div{display:flex;flex-direction:column}.tl small{color:var(--muted);margin-top:3px}.lenses{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.lens{border:1px solid var(--line);background:#ebe7de}.lens header{font:12px ui-monospace,monospace;text-transform:uppercase;padding:9px 12px;border-bottom:1px solid var(--line)}.lens.high header{color:var(--accent)}.lens.attention header{color:var(--warn)}.lens.info header{color:var(--ok)}.lens ul{padding:4px 28px 12px 32px}.pub{border-bottom:1px solid var(--line);padding:12px 0}.pub>div{display:flex;justify-content:space-between;gap:10px}.pub span{font:11px ui-monospace,monospace;color:var(--muted)}.pub p{font-size:14px;color:#3f4250}.note{border-left:3px solid var(--accent);padding:12px 15px;background:#ebe7de;color:#444753}.foot{font:11px ui-monospace,monospace;color:var(--muted);margin-top:30px}@media(max-width:650px){.meta,.stats,.lenses{grid-template-columns:1fr 1fr}.tl{grid-template-columns:1fr;gap:3px}}@media print{.cover{-webkit-print-color-adjust:exact;print-color-adjust:exact}}'+
  '</style></head><body><section class="cover"><div class="wrap"><span class="eyebrow">PredictLM · Lexis Processos · DataJud + DJEN</span><h1>'+esc(bundle.processNumber)+'</h1><p>'+esc(bundle.summary.headline)+'</p><div class="meta"><div><b>Tribunal</b>'+esc(bundle.tribunalLabel)+'</div><div><b>Status público</b>'+esc(bundle.summary.status)+'</div><div><b>Movimentos</b>'+bundle.summary.movementCount+'</div><div><b>Publicações DJEN</b>'+bundle.summary.publicationCount+'</div></div></div></section>'+
  '<main class="main"><section><span class="eyebrow">01 · Resumo</span><h2>Leitura processual pública</h2><p class="summary">'+esc(bundle.summary.status)+'.</p><div class="stats"><div class="stat"><span>Classe</span><b>'+esc(bundle.datajud.class?.name||'—')+'</b></div><div class="stat"><span>Órgão</span><b>'+esc(bundle.datajud.court?.name||'—')+'</b></div><div class="stat"><span>Ajuizamento</span><b>'+esc(date(bundle.datajud.filedAt))+'</b></div><div class="stat"><span>Atualização</span><b>'+esc(date(bundle.datajud.lastUpdate))+'</b></div></div></section>'+
  '<section class="section"><span class="eyebrow">02 · Linha do tempo</span><h2>Movimentos e publicações</h2>'+rows+'</section>'+
  '<section class="section"><span class="eyebrow">03 · Council revisional</span><h2>Cinco lentes operacionais</h2><div class="lenses">'+lenses+'</div></section>'+
  '<section class="section"><span class="eyebrow">04 · DJEN</span><h2>Publicações encontradas</h2>'+(pubs||'<p>Nenhuma publicação retornada na consulta atual.</p>')+'</section>'+
  '<section class="section"><span class="eyebrow">05 · Limitações</span><div class="note">'+esc(bundle.summary.caveats.join(' '))+'</div><p class="foot">Gerado em '+esc(date(bundle.fetchedAt))+'. Fonte de capa/movimentos: API Pública DataJud/CNJ. Fonte de comunicações: DJEN/Comunica PJe/CNJ. Este documento organiza dados públicos e não substitui a leitura dos autos.</p></section></main></body></html>';
}
